import type { Metadata } from "next";
import {
  PageList,
  PageParagraph,
  PageSectionHeading,
  PageShell
} from "@/components/ui/page-shell";

export const metadata: Metadata = {
  title: "Privacy Policy · Smart Jotter",
  description:
    "How Smart Jotter collects, uses, and protects your personal information."
};

export default function PrivacyPage() {
  return (
    <PageShell
      eyebrow="Legal"
      title="Privacy Policy"
      subtitle="Your privacy matters. This policy explains what we collect, why, and how we keep it safe."
    >
      <p className="text-sm text-slate-500 dark:text-slate-400">
        Last updated: {new Date().toLocaleDateString()}
      </p>

      <PageSectionHeading>1. Who we are</PageSectionHeading>
      <PageParagraph>
        Smart Jotter ("we", "us") operates the website and
        note-taking service at smartjotter.com (the "Service"). This
        Privacy Policy explains how we handle your personal information.
      </PageParagraph>

      <PageSectionHeading>2. Information we collect</PageSectionHeading>
      <PageList
        items={[
          "Account information: your name, email address, and authentication details when you sign up.",
          "Content you create: notes and other material you save in the Service.",
          "Usage information: how you use features, AI credits consumed, and interactions with the app.",
          "Payment information: payments are processed by Paystack. We receive limited transaction status (such as success/failure and plan) to manage your subscription, but we do not store your full card details.",
          "Technical information: IP address, browser type, and device information used to keep the Service secure and reliable."
        ]}
      />

      <PageSectionHeading>3. How we use your information</PageSectionHeading>
      <PageList
        items={[
          "To provide, maintain, and improve the Service.",
          "To create and manage your account and authenticate you.",
          "To process payments and manage subscriptions.",
          "To provide AI features you request, such as summaries, suggestions, transcription, flashcards, and quizzes.",
          "To communicate with you about your account, support requests, and important updates.",
          "To monitor for fraud, abuse, and security threats."
        ]}
      />

      <PageSectionHeading>4. AI features and your content</PageSectionHeading>
      <PageParagraph>
        AI features process your notes only to deliver the specific feature you
        requested. We do not use your private notes to train AI models. Output
        generated by AI may occasionally be inaccurate, so please review it
        before relying on it.
      </PageParagraph>

      <PageSectionHeading>5. Payments</PageSectionHeading>
      <PageParagraph>
        Subscription payments are handled by Paystack, our payment processor.
        Paystack collects and processes your payment details according to its
        own privacy and security standards. We only receive the information
        needed to activate and manage your subscription.
      </PageParagraph>

      <PageSectionHeading>6. Data sharing</PageSectionHeading>
      <PageParagraph>
        We do not sell your personal data. We share information only as
        necessary to operate the Service, including with:
      </PageParagraph>
      <PageList
        items={[
          "Service providers (such as our database, hosting, AI, and payment partners) under appropriate agreements.",
          "Authorities or third parties where required by law, regulation, or to protect our rights and users."
        ]}
      />

      <PageSectionHeading>7. Data retention</PageSectionHeading>
      <PageParagraph>
        We keep your information for as long as your account is active or as
        needed to provide the Service. When you delete content or close your
        account, we remove or anonymize the associated data within a reasonable
        period, except where we are legally required to retain it.
      </PageParagraph>

      <PageSectionHeading>8. Your rights</PageSectionHeading>
      <PageList
        items={[
          "Access, correct, or update your account information.",
          "Request deletion of your account and associated content.",
          "Object to or restrict certain processing of your data.",
          "Withdraw consent where we rely on it, without affecting prior processing."
        ]}
      />
      <PageParagraph>
        To exercise any of these rights, email{" "}
        <a
          href="mailto:support@smartjotter.com"
          className="font-medium text-slate-700 underline transition hover:text-ink dark:text-slate-200 dark:hover:text-white"
        >
          support@smartjotter.com
        </a>
        .
      </PageParagraph>

      <PageSectionHeading>9. Security</PageSectionHeading>
      <PageParagraph>
        We use reasonable technical and organizational measures to protect your
        data, including encrypted authentication and access controls. No method
        of transmission or storage is completely secure, but we work to
        safeguard your information.
      </PageParagraph>

      <PageSectionHeading>10. Children's privacy</PageSectionHeading>
      <PageParagraph>
        The Service is not intended for children under 13 (or the minimum age
        required in their country). We do not knowingly collect personal
        information from children. If you believe a child has provided us
        information, contact us so we can delete it.
      </PageParagraph>

      <PageSectionHeading>11. International transfers</PageSectionHeading>
      <PageParagraph>
        Your information may be processed in countries other than your own. By
        using the Service, you consent to such transfers in accordance with
        this Privacy Policy.
      </PageParagraph>

      <PageSectionHeading>12. Changes to this policy</PageSectionHeading>
      <PageParagraph>
        We may update this Privacy Policy from time to time. We will post the
        revised version on this page and update the "Last updated"
        date. Material changes will be highlighted where practical.
      </PageParagraph>

      <PageSectionHeading>13. Contact</PageSectionHeading>
      <PageParagraph>
        Questions about your privacy? Email us at{" "}
        <a
          href="mailto:support@smartjotter.com"
          className="font-medium text-slate-700 underline transition hover:text-ink dark:text-slate-200 dark:hover:text-white"
        >
          support@smartjotter.com
        </a>
        .
      </PageParagraph>
    </PageShell>
  );
}