/**
 * Paystack server-side helpers.
 *
 * Shared by:
 *   - /api/paystack/verify  (client-initiated verification after the popup)
 *   - /api/paystack/webhook (backup safety net for charge.success events)
 *
 * Security:
 *   - Transactions are NEVER trusted from the client alone. We always call
 *     Paystack's verify endpoint with the secret key before granting anything.
 *   - The webhook additionally validates the HMAC signature using the secret.
 */

import { createClient } from "@supabase/supabase-js";
import { getPaystackSecretKey, getSupabaseServiceRoleKey, getSupabaseUrl } from "@/lib/env";
import { logServerError } from "@/lib/server/errors";
import {
  AI_SUBSCRIPTION_PLANS,
  STT_TOPUP_PLANS,
  SUBSCRIPTION_PLANS,
  type AiPlanId,
  type PlanId,
  type SttTopupId
} from "@/lib/config/plans";
import type { PaystackMetadata } from "@/lib/paystack/types";

// Re-export so existing server-side callers can import everything from
// "@/lib/paystack/server" without reaching into the types module.
export type { PaystackMetadata } from "@/lib/paystack/types";

/* -------------------------------------------------------------------------- */
/* Types                                                                       */
/* -------------------------------------------------------------------------- */

/** Subset of Paystack's transaction.verify response that we depend on. */
type PaystackVerificationData = {
  status: boolean;
  amount: number; // in kobo/cent (smallest currency unit)
  currency: string;
  reference: string;
  customer: {
    email: string;
    customer_code?: string;
  };
  authorization?: {
    authorization_code?: string;
    card_type?: string;
    last4?: string;
    exp_month?: string | number;
    exp_year?: string | number;
    bank?: string;
    reusable?: boolean;
  };
  metadata?: unknown;
};

/* -------------------------------------------------------------------------- */
/* Admin Supabase client                                                       */
/* -------------------------------------------------------------------------- */

/**
 * Builds a service-role Supabase client that bypasses RLS. Used to update
 * entitlements after a verified payment. This mirrors the pattern in the
 * signup route.
 */
export function createServiceRoleSupabaseClient() {
  return createClient(getSupabaseUrl(), getSupabaseServiceRoleKey(), {
    // Smart Jotter tables live in the dedicated "jotter" schema of the shared
    // Supabase project (see lib/supabase/browser.ts).
    db: { schema: "jotter" },
    auth: { autoRefreshToken: false, persistSession: false }
  });
}

/* -------------------------------------------------------------------------- */
/* Reference validation (injection / SSRF defense)                             */
/* -------------------------------------------------------------------------- */

/**
 * Paystack transaction references are generated by us (see the client helper)
 * and are alphanumeric with dashes/underscores only. We validate the format
 * before placing the reference into the verify URL to prevent path traversal,
 * CRLF injection, or SSRF-style payloads from reaching the outbound request.
 *
 * References we generate look like: sj_stt_stt240_1699999999_abc123
 */
const PAYSTACK_REFERENCE_RE = /^[A-Za-z0-9_-]{4,120}$/;

export function isValidPaystackReference(reference: string): boolean {
  return PAYSTACK_REFERENCE_RE.test(reference);
}

/* -------------------------------------------------------------------------- */
/* Verify                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Calls Paystack's transaction.verify endpoint.
 *
 * Docs: https://paystack.com/docs/api/transaction/#verify
 *
 * Returns the normalised verification data on success, or throws on any
 * non-success / untrusted response.
 */
export async function verifyPaystackTransaction(reference: string): Promise<PaystackVerificationData> {
  if (!isValidPaystackReference(reference)) {
    throw new Error("Invalid transaction reference format.");
  }

  const secret = getPaystackSecretKey();

  const response = await fetch(
    `https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,
    {
      method: "GET",
      headers: {
        Authorization: `Bearer ${secret}`,
        Accept: "application/json"
      },
      cache: "no-store"
    }
  );

  if (!response.ok) {
    const text = await response.text().catch(() => "");
    throw new Error(
      `Paystack verify HTTP ${response.status}: ${text || response.statusText}`
    );
  }

  const json = (await response.json()) as {
    status: boolean;
    message?: string;
    data?: Partial<PaystackVerificationData> & { status?: string };
  };

  // Paystack wraps the real verification in json.data.status === "success".
  if (!json.status || !json.data || json.data.status !== "success") {
    throw new Error(
      `Paystack transaction not successful: ${json.message ?? "unknown error"}`
    );
  }

  const data = json.data;
  const amount = typeof data.amount === "number" ? data.amount : Number(data.amount);

  return {
    status: true,
    amount,
    currency: data.currency ?? "GHS",
    reference: data.reference ?? reference,
    customer: {
      email: data.customer?.email ?? "",
      customer_code: data.customer?.customer_code
    },
    authorization: data.authorization,
    metadata: data.metadata
  };
}

/* -------------------------------------------------------------------------- */
/* Plan validation (amount + metadata sanity check)                           */
/* -------------------------------------------------------------------------- */

/** Returns the expected prices (in major currency units) for a plan. */
function getPlanPrices(
  planType: "stt" | "ai" | "stt_topup",
  planId: PlanId | AiPlanId | SttTopupId
): { priceGhs: number; priceUsd: number } {
  if (planType === "stt") {
    const plan = SUBSCRIPTION_PLANS.find((p) => p.id === planId);
    if (!plan) {
      throw new Error(`Unknown Speech-to-Text plan: ${planId}`);
    }
    return { priceGhs: plan.priceGhs, priceUsd: plan.priceUsd };
  }

  if (planType === "stt_topup") {
    const plan = STT_TOPUP_PLANS.find((p) => p.id === planId);
    if (!plan) {
      throw new Error(`Unknown Speech-to-Text top-up: ${planId}`);
    }
    // Top-ups are GHS-only for now; no USD equivalent is offered.
    return { priceGhs: plan.priceGhs, priceUsd: plan.priceGhs };
  }

  const plan = AI_SUBSCRIPTION_PLANS.find((p) => p.id === planId);
  if (!plan) {
    throw new Error(`Unknown AI Writing Assist plan: ${planId}`);
  }
  return { priceGhs: plan.priceGhs, priceUsd: plan.priceUsd };
}

/**
 * Safely extracts and validates the plan metadata attached to the transaction.
 * Throws if the metadata is missing or references an unknown plan.
 */
export function extractMetadata(raw: unknown): PaystackMetadata {
  const meta = raw as Partial<PaystackMetadata> | undefined;

  if (!meta || typeof meta !== "object") {
    throw new Error("Transaction metadata is missing.");
  }

  const userId = meta.user_id;
  const planType = meta.plan_type;
  const planId = meta.plan_id;

  if (!userId || typeof userId !== "string") {
    throw new Error("Transaction metadata is missing user_id.");
  }

  if (!planId || typeof planId !== "string") {
    throw new Error("Transaction metadata is missing plan_id.");
  }

  if (planType !== "stt" && planType !== "ai" && planType !== "stt_topup") {
    throw new Error(`Invalid plan_type in metadata: ${String(planType)}`);
  }

  if (planType === "stt") {
    if (!SUBSCRIPTION_PLANS.some((p) => p.id === planId)) {
      throw new Error(`Invalid Speech-to-Text plan_id: ${String(planId)}`);
    }
  } else if (planType === "stt_topup") {
    if (!STT_TOPUP_PLANS.some((p) => p.id === planId)) {
      throw new Error(`Invalid Speech-to-Text top-up plan_id: ${String(planId)}`);
    }
  } else {
    if (!AI_SUBSCRIPTION_PLANS.some((p) => p.id === planId)) {
      throw new Error(`Invalid AI Writing Assist plan_id: ${String(planId)}`);
    }
  }

  return { user_id: userId, plan_type: planType, plan_id: planId };
}

/**
 * Confirms the verified transaction's amount matches the expected plan price
 * for its currency. African visitors are charged in GHS; visitors outside
 * Africa are charged in USD at the fixed rate in lib/config/plans.ts.
 * Paystack amounts are in the smallest currency unit (pesewas/cents), so
 * 50 GHS is returned as 5000 and 20 USD as 2000.
 */
export function assertAmountMatches(
  data: PaystackVerificationData,
  metadata: PaystackMetadata
) {
  const prices = getPlanPrices(metadata.plan_type, metadata.plan_id);
  const currency = data.currency.toUpperCase();

  if (currency !== "GHS" && currency !== "USD") {
    throw new Error(`Currency mismatch: paid in ${currency}, expected GHS or USD.`);
  }

  // Top-ups are GHS-only: reject any USD payment carrying a top-up id so a
  // forged metadata pair can never activate minutes at the wrong price.
  if (metadata.plan_type === "stt_topup" && currency !== "GHS") {
    throw new Error(
      `Currency mismatch: Extra Minutes are charged in GHS, paid in ${currency}.`
    );
  }

  const expectedMajor = currency === "USD" ? prices.priceUsd : prices.priceGhs;
  const expectedMinor = Math.round(expectedMajor * 100);

  if (data.amount !== expectedMinor) {
    throw new Error(
      `Amount mismatch: paid ${data.amount} minor units, expected ${expectedMinor} (${expectedMajor} ${currency}).`
    );
  }
}

/* -------------------------------------------------------------------------- */
/* Idempotency ledger (replay-attack defense)                                  */
/* -------------------------------------------------------------------------- */

/**
 * Records a processed transaction in `sj_paystack_transactions`.
 *
 * Returns `true` if this is a NEW transaction (caller should grant entitlements),
 * or `false` if the transaction was ALREADY processed (caller should skip the
 * grant but still return success to the client / Paystack).
 *
 * This closes a replay gap where the same valid reference could be submitted
 * repeatedly to keep refreshing subscription expiry dates without paying again.
 */
export async function isTransactionProcessed(
  supabase: ReturnType<typeof createServiceRoleSupabaseClient>,
  reference: string
): Promise<boolean> {
  const { data, error } = await supabase
    .from("sj_paystack_transactions")
    .select("reference")
    .eq("reference", reference)
    .maybeSingle();

  if (error) {
    // Fail closed: if we can't check the ledger, don't silently grant.
    throw new Error(`Ledger check failed: ${error.message}`);
  }

  return Boolean(data);
}

/**
 * Inserts the transaction into the ledger after a successful grant. Uses
 * `onConflict: "reference"` with no update to guarantee idempotency even
 * under concurrent verify + webhook delivery.
 */
export async function markTransactionProcessed(
  supabase: ReturnType<typeof createServiceRoleSupabaseClient>,
  reference: string,
  metadata: PaystackMetadata,
  amountMinor: number,
  currency: string
): Promise<void> {
  const { error } = await supabase
    .from("sj_paystack_transactions")
    .upsert(
      {
        reference,
        user_id: metadata.user_id,
        plan_type: metadata.plan_type,
        plan_id: metadata.plan_id,
        amount_minor: amountMinor,
        currency: currency.toUpperCase()
      },
      { onConflict: "reference", ignoreDuplicates: true }
    );

  if (error) {
    // Non-fatal: the grant already happened. Log but don't throw, since the
    // entitlements are already active.
    logServerError("paystack-ledger-insert", error);
  }
}

/* -------------------------------------------------------------------------- */
/* Grant entitlements                                                          */
/* -------------------------------------------------------------------------- */

/** Returns YYYY-MM-DD `validityDays` from now (UTC). */
function computeExpiryDate(validityDays: number): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() + validityDays);
  return d.toISOString().slice(0, 10);
}

/**
 * Updates `sj_user_entitlements` for the paid plan. This is the single source
 * of truth for granting access after a verified Paystack transaction.
 *
 * Also records the plan id per track (`stt_last_plan_id` / `ai_last_plan_id`)
 * so the daily auto-renew job knows which plan to re-charge.
 *
 * Idempotent: it always SETS the plan columns (not increments), so a duplicate
 * verify / webhook call simply refreshes the same entitlements rather than
 * stacking.
 */
export async function grantPlanEntitlements(
  supabase: ReturnType<typeof createServiceRoleSupabaseClient>,
  metadata: PaystackMetadata
): Promise<{ activated: "stt" | "ai"; planId: PlanId | AiPlanId }> {
  if (metadata.plan_type === "stt") {
    const plan = SUBSCRIPTION_PLANS.find((p) => p.id === metadata.plan_id)!;
    const minutesAllotted = plan.durationSeconds / 60;

    const { error } = await supabase
      .from("sj_user_entitlements")
      .upsert(
        {
          user_id: metadata.user_id,
          subscription_status: "active",
          subscription_expiry: computeExpiryDate(plan.validityDays),
          subscription_minutes_allotted: minutesAllotted,
          subscription_minutes_used: 0,
          stt_last_plan_id: plan.id
        },
        { onConflict: "user_id" }
      );

    if (error) {
      throw new Error(
        `Could not activate Speech-to-Text plan: ${error.message}`
      );
    }

    return { activated: "stt", planId: plan.id };
  }

  // AI Writing Assist plan
  const plan = AI_SUBSCRIPTION_PLANS.find((p) => p.id === metadata.plan_id)!;

  const { error } = await supabase
    .from("sj_user_entitlements")
    .upsert(
      {
        user_id: metadata.user_id,
        ai_subscription_status: "active",
        ai_subscription_expiry: computeExpiryDate(plan.validityDays),
        credits_allotted: plan.credits,
        credits_used: 0,
        ai_last_plan_id: plan.id
      },
      { onConflict: "user_id" }
    );

  if (error) {
    throw new Error(
      `Could not activate AI Writing Assist plan: ${error.message}`
    );
  }

  return { activated: "ai", planId: plan.id };
}

/**
 * Credits purchased Extra Minutes after a verified top-up transaction.
 *
 * Unlike `grantPlanEntitlements`, this INCREMENTS the balance (top-ups stack)
 * and deliberately does NOT touch `stt_last_plan_id` — the auto-renew cron
 * selects rows by last-plan id, so a top-up can never be re-charged.
 */
export async function grantTopupMinutes(
  supabase: ReturnType<typeof createServiceRoleSupabaseClient>,
  metadata: PaystackMetadata
): Promise<{ activated: "stt_topup"; planId: SttTopupId; secondsAdded: number }> {
  const plan = STT_TOPUP_PLANS.find((p) => p.id === metadata.plan_id)!;

  // Atomic SQL increment (jotter.add_purchased_seconds, service_role only):
  // inserts the row if missing, adds to the existing balance otherwise.
  const { error } = await supabase.rpc("add_purchased_seconds", {
    input_user_id: metadata.user_id,
    input_seconds: plan.seconds
  });

  if (error) {
    throw new Error(`Could not credit Extra Minutes: ${error.message}`);
  }

  return { activated: "stt_topup", planId: plan.id, secondsAdded: plan.seconds };
}

/* -------------------------------------------------------------------------- */
/* Saved card authorization (auto-renew)                                       */
/* -------------------------------------------------------------------------- */

/**
 * Stores the card authorization from a successful transaction so the plan can
 * be re-charged at renewal time. Best-effort: a failure here never blocks the
 * grant — auto-renew simply won't be available for this payment.
 *
 * Only reusable authorizations are saved (single-use ones can't be charged
 * again and are useless for renewal).
 */
export async function captureAuthorization(
  supabase: ReturnType<typeof createServiceRoleSupabaseClient>,
  data: PaystackVerificationData,
  metadata: PaystackMetadata
): Promise<void> {
  const auth = data.authorization;
  const code = auth?.authorization_code;

  if (!code || auth?.reusable === false) {
    return;
  }

  const currency = data.currency.toUpperCase();
  if (currency !== "GHS" && currency !== "USD") {
    return;
  }

  const { error } = await supabase
    .from("sj_payment_authorizations")
    .upsert(
      {
        user_id: metadata.user_id,
        authorization_code: code,
        customer_code: data.customer.customer_code ?? null,
        email: data.customer.email,
        card_type: auth?.card_type ?? null,
        last4: auth?.last4 ?? null,
        exp_month: auth?.exp_month != null ? String(auth.exp_month) : null,
        exp_year: auth?.exp_year != null ? String(auth.exp_year) : null,
        bank: auth?.bank ?? null,
        currency
      },
      { onConflict: "user_id" }
    );

  if (error) {
    logServerError("paystack-authorization-capture", error);
  }
}

/** Result of a renewal charge attempt. */
export type ChargeAuthorizationResult =
  | { ok: true; reference: string; amountMinor: number; currency: "GHS" | "USD" }
  | { ok: false; error: string };

/**
 * Re-charges a saved card via Paystack's charge_authorization endpoint.
 *
 * Docs: https://paystack.com/docs/payments/accept-payments/#charge-authorization
 *
 * Charges the plan's current price in the currency the card was originally
 * used with. Returns ok:false (never throws) for payment failures so the
 * caller can expire the plan quietly.
 */
export async function chargeAuthorization(
  supabase: ReturnType<typeof createServiceRoleSupabaseClient>,
  userId: string,
  metadata: PaystackMetadata
): Promise<ChargeAuthorizationResult> {
  // Load the saved authorization (service role bypasses RLS).
  const { data: saved, error: loadError } = await supabase
    .from("sj_payment_authorizations")
    .select("authorization_code, customer_code, email, currency")
    .eq("user_id", userId)
    .maybeSingle();

  if (loadError || !saved) {
    return { ok: false, error: loadError?.message ?? "No saved card on file." };
  }

  const currency = (saved.currency as string).toUpperCase();
  if (currency !== "GHS" && currency !== "USD") {
    return { ok: false, error: `Unsupported saved currency: ${currency}` };
  }

  const prices = getPlanPrices(metadata.plan_type, metadata.plan_id);
  const amountMinor = Math.round(
    (currency === "USD" ? prices.priceUsd : prices.priceGhs) * 100
  );

  const reference = `sj_renew_${metadata.plan_type}_${Date.now()}_${Math.random()
    .toString(36)
    .slice(2, 8)}`;

  const secret = getPaystackSecretKey();
  const response = await fetch("https://api.paystack.co/transaction/charge_authorization", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${secret}`,
      "Content-Type": "application/json",
      Accept: "application/json"
    },
    body: JSON.stringify({
      authorization_code: saved.authorization_code,
      email: saved.email,
      amount: amountMinor,
      currency,
      reference,
      metadata: {
        user_id: userId,
        plan_type: metadata.plan_type,
        plan_id: metadata.plan_id
      }
    }),
    cache: "no-store"
  });

  const json = (await response.json().catch(() => null)) as {
    status?: boolean;
    message?: string;
    data?: { status?: string; reference?: string };
  } | null;

  if (!response.ok || !json?.status || !json.data) {
    return {
      ok: false,
      error: `Paystack charge_authorization HTTP ${response.status}: ${json?.message ?? "no response"}`
    };
  }

  // Pending/failed states are both non-success for our purposes. A pending
  // charge (rare for card auths, possible with OTP flows) is treated as a
  // failure — the user can resubscribe manually if it doesn't complete.
  if (json.data.status !== "success") {
    return {
      ok: false,
      error: `Renewal charge not successful: ${json.data.status ?? json.message ?? "unknown"}`
    };
  }

  return {
    ok: true,
    reference: json.data.reference ?? reference,
    amountMinor,
    currency: currency as "GHS" | "USD"
  };
}

/* -------------------------------------------------------------------------- */
/* Webhook signature                                                           */
/* -------------------------------------------------------------------------- */

/**
 * Verifies a Paystack webhook signature (HMAC-SHA512) using the secret key.
 *
 * Docs: https://paystack.com/docs/webhooks/
 *
 * The signature header looks like:
 *   x-paystack-signature: <hmac hex>
 *
 * and is computed over the raw request body with the secret key.
 *
 * Uses Node's built-in crypto (available on the server in Next.js route
 * handlers running on Node runtime — these routes are not edge).
 */
export async function verifyWebhookSignature(
  rawBody: string,
  signatureHeader: string | null
): Promise<boolean> {
  if (!signatureHeader) {
    return false;
  }

  const crypto = await import("node:crypto");
  const secret = getPaystackSecretKey();

  const computed = crypto
    .createHmac("sha512", secret)
    .update(rawBody)
    .digest("hex");

  // Use timingSafeEqual to avoid trivial string-comparison leaks.
  try {
    const a = Buffer.from(computed, "utf8");
    const b = Buffer.from(signatureHeader, "utf8");
    if (a.length !== b.length) {
      return false;
    }
    return crypto.timingSafeEqual(a, b);
  } catch (error) {
    logServerError("paystack-webhook-signature", error);
    return false;
  }
}